# SlickEdit generated file.  Do not edit this file except in designated areas.

# Make command to use for dependencies
MAKE=make
RM=rm
MKDIR=mkdir

# -----Begin user-editable area-----

# -----End user-editable area-----

#
# Configuration: LinaroArmDebug
#
OUTDIR=LinaroArmDebug
OUTFILE=/soc_dev/common/uio_helper/libuio_helper.lib
CFG_INC=-Isrc 
CFG_LIB=
CFG_OBJ=
COMMON_OBJ=$(OUTDIR)/uio_find_devices.o \
	$(OUTDIR)/uio_find_devices_byname.o $(OUTDIR)/uio_free.o \
	$(OUTDIR)/uio_get_all_info.o $(OUTDIR)/uio_get_device_attributes.o \
	$(OUTDIR)/uio_get_event_count.o $(OUTDIR)/uio_get_mem_addr.o \
	$(OUTDIR)/uio_get_mem_size.o $(OUTDIR)/uio_get_name.o \
	$(OUTDIR)/uio_get_version.o $(OUTDIR)/uio_line_from_file.o \
	$(OUTDIR)/uio_mmap.o $(OUTDIR)/uio_munmap.o \
	$(OUTDIR)/uio_num_from_filename.o $(OUTDIR)/uio_single_mmap.o \
	$(OUTDIR)/uio_single_munmap.o 
OBJ=$(COMMON_OBJ) $(CFG_OBJ)
ALL_OBJ=$(OUTDIR)/uio_find_devices.o \
	$(OUTDIR)/uio_find_devices_byname.o $(OUTDIR)/uio_free.o \
	$(OUTDIR)/uio_get_all_info.o $(OUTDIR)/uio_get_device_attributes.o \
	$(OUTDIR)/uio_get_event_count.o $(OUTDIR)/uio_get_mem_addr.o \
	$(OUTDIR)/uio_get_mem_size.o $(OUTDIR)/uio_get_name.o \
	$(OUTDIR)/uio_get_version.o $(OUTDIR)/uio_line_from_file.o \
	$(OUTDIR)/uio_mmap.o $(OUTDIR)/uio_munmap.o \
	$(OUTDIR)/uio_num_from_filename.o $(OUTDIR)/uio_single_mmap.o \
	$(OUTDIR)/uio_single_munmap.o 

COMPILE="$(CROSS_COMPILE)gcc" -c   -O0 -g3 -fPIC -mcpu=cortex-a7 -mfpu=neon-vfpv4 -mfloat-abi=hard -o "$(OUTDIR)/$(*F).o" $(CFG_INC) $<
LINK=ar -rs  "$(OUTFILE)" $(OBJ)

# Pattern rules
$(OUTDIR)/%.o : src/%.c
	$(COMPILE)

# Build rules
all: $(OUTFILE)

$(OUTFILE): $(OUTDIR)  $(OBJ)
	$(LINK)
	-./post_build.sh /soc_dev/common/uio_helper/libuio_helper.so

$(OUTDIR):
	$(MKDIR) -p "$(OUTDIR)"

# Rebuild this project
rebuild: cleanall all

# Clean this project
clean:
	$(RM) -f $(OUTFILE)
	$(RM) -f $(OBJ)

# Clean this project and all dependencies
cleanall: clean
